FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at
# RUN pip uninstall -y opencv-python-headless opencv-python
# RUN pip install opencv-python


# # Expose the port the app runs on (optional, adjust if needed)
# EXPOSE 8000

# # Command to run the app
# CMD ["python3", "app.py"]